export const communityMapData = {
  procedure: {
    procedureId: '276429',
    voted: false,
    communityVotes: {
      constituencies: [
        {
          yes: 0,
          no: 14,
          abstination: 0,
          total: 14,
          constituency: '153',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '42',
        },
        {
          yes: 0,
          no: 7,
          abstination: 1,
          total: 8,
          constituency: '217',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '192',
        },
        {
          yes: 1,
          no: 0,
          abstination: 0,
          total: 1,
          constituency: '135',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '127',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '17',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '163',
        },
        {
          yes: 1,
          no: 8,
          abstination: 0,
          total: 9,
          constituency: '8',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '246',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '166',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '296',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '63',
        },
        {
          yes: 1,
          no: 3,
          abstination: 0,
          total: 4,
          constituency: '72',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '44',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '250',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '39',
        },
        {
          yes: 2,
          no: 19,
          abstination: 0,
          total: 21,
          constituency: '76',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '35',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '168',
        },
        {
          yes: 0,
          no: 5,
          abstination: 1,
          total: 6,
          constituency: '65',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '26',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '31',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '198',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '210',
        },
        {
          yes: 1,
          no: 4,
          abstination: 1,
          total: 6,
          constituency: '186',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '148',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '194',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '47',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '243',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '147',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '201',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '118',
        },
        {
          yes: 0,
          no: 17,
          abstination: 0,
          total: 17,
          constituency: '14',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '59',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '177',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '254',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '129',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '228',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '11',
        },
        {
          yes: 0,
          no: 13,
          abstination: 0,
          total: 13,
          constituency: '86',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '270',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '174',
        },
        {
          yes: 1,
          no: 2,
          abstination: 0,
          total: 3,
          constituency: '55',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '23',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '51',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '36',
        },
        {
          yes: 1,
          no: 8,
          abstination: 1,
          total: 10,
          constituency: '226',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '200',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '117',
        },
        {
          yes: 0,
          no: 3,
          abstination: 1,
          total: 4,
          constituency: '126',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '116',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '155',
        },
        {
          yes: 2,
          no: 11,
          abstination: 0,
          total: 13,
          constituency: '158',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '25',
        },
        {
          yes: 2,
          no: 8,
          abstination: 0,
          total: 10,
          constituency: '69',
        },
        {
          yes: 0,
          no: 18,
          abstination: 0,
          total: 18,
          constituency: '75',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '121',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '276',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '230',
        },
        {
          yes: 1,
          no: 12,
          abstination: 0,
          total: 13,
          constituency: '259',
        },
        {
          yes: 0,
          no: 11,
          abstination: 1,
          total: 12,
          constituency: '291',
        },
        {
          yes: 0,
          no: 5,
          abstination: 1,
          total: 6,
          constituency: '255',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '278',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '33',
        },
        {
          yes: 1,
          no: 2,
          abstination: 0,
          total: 3,
          constituency: '227',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '279',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '283',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '27',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '252',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '124',
        },
        {
          yes: 2,
          no: 5,
          abstination: 0,
          total: 7,
          constituency: '81',
        },
        {
          yes: 2,
          no: 4,
          abstination: 0,
          total: 6,
          constituency: '172',
        },
        {
          yes: 0,
          no: 11,
          abstination: 0,
          total: 11,
          constituency: '277',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '179',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '16',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '111',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '272',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '273',
        },
        {
          yes: 1,
          no: 3,
          abstination: 0,
          total: 4,
          constituency: '139',
        },
        {
          yes: 1,
          no: 2,
          abstination: 0,
          total: 3,
          constituency: '89',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '45',
        },
        {
          yes: 0,
          no: 11,
          abstination: 0,
          total: 11,
          constituency: '4',
        },
        {
          yes: 0,
          no: 16,
          abstination: 0,
          total: 16,
          constituency: '83',
        },
        {
          yes: 1,
          no: 3,
          abstination: 1,
          total: 5,
          constituency: '92',
        },
        {
          yes: 1,
          no: 7,
          abstination: 1,
          total: 9,
          constituency: '112',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '235',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '96',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '215',
        },
        {
          yes: 0,
          no: 2,
          abstination: 1,
          total: 3,
          constituency: '70',
        },
        {
          yes: 0,
          no: 4,
          abstination: 1,
          total: 5,
          constituency: '184',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '206',
        },
        {
          yes: 2,
          no: 5,
          abstination: 0,
          total: 7,
          constituency: '157',
        },
        {
          yes: 1,
          no: 8,
          abstination: 0,
          total: 9,
          constituency: '220',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '173',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '46',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '38',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '43',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '225',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '180',
        },
        {
          yes: 1,
          no: 3,
          abstination: 1,
          total: 5,
          constituency: '297',
        },
        {
          yes: 1,
          no: 5,
          abstination: 1,
          total: 7,
          constituency: '223',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '299',
        },
        {
          yes: 1,
          no: 8,
          abstination: 0,
          total: 9,
          constituency: '187',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '109',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '204',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '88',
        },
        {
          yes: 2,
          no: 3,
          abstination: 0,
          total: 5,
          constituency: '176',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '287',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '164',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '219',
        },
        {
          yes: 0,
          no: 6,
          abstination: 1,
          total: 7,
          constituency: '10',
        },
        {
          yes: 2,
          no: 12,
          abstination: 1,
          total: 15,
          constituency: '61',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '232',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '122',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '68',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '41',
        },
        {
          yes: 0,
          no: 7,
          abstination: 1,
          total: 8,
          constituency: '91',
        },
        {
          yes: 0,
          no: 15,
          abstination: 0,
          total: 15,
          constituency: '264',
        },
        {
          yes: 3,
          no: 3,
          abstination: 0,
          total: 6,
          constituency: '142',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '71',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '290',
        },
        {
          yes: 1,
          no: 2,
          abstination: 1,
          total: 4,
          constituency: '24',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '12',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '66',
        },
        {
          yes: 0,
          no: 5,
          abstination: 1,
          total: 6,
          constituency: '280',
        },
        {
          yes: 1,
          no: 1,
          abstination: 0,
          total: 2,
          constituency: '2',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '114',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '150',
        },
        {
          yes: 1,
          no: 3,
          abstination: 0,
          total: 4,
          constituency: '221',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '105',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '170',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '28',
        },
        {
          yes: 1,
          no: 13,
          abstination: 1,
          total: 15,
          constituency: '84',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '93',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '101',
        },
        {
          yes: 1,
          no: 14,
          abstination: 0,
          total: 15,
          constituency: '160',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '94',
        },
        {
          yes: 3,
          no: 4,
          abstination: 1,
          total: 8,
          constituency: '251',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '211',
        },
        {
          yes: 1,
          no: 5,
          abstination: 1,
          total: 7,
          constituency: '199',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '224',
        },
        {
          yes: 1,
          no: 10,
          abstination: 0,
          total: 11,
          constituency: '271',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '67',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '22',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '154',
        },
        {
          yes: 3,
          no: 14,
          abstination: 0,
          total: 17,
          constituency: '79',
        },
        {
          yes: 2,
          no: 7,
          abstination: 0,
          total: 9,
          constituency: '62',
        },
        {
          yes: 0,
          no: 6,
          abstination: 1,
          total: 7,
          constituency: '196',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '37',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '181',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '239',
        },
        {
          yes: 1,
          no: 4,
          abstination: 1,
          total: 6,
          constituency: '203',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '209',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '208',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '13',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '156',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '175',
        },
        {
          yes: 2,
          no: 5,
          abstination: 1,
          total: 8,
          constituency: '258',
        },
        {
          yes: 0,
          no: 15,
          abstination: 0,
          total: 15,
          constituency: '257',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '53',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '216',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '21',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '99',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '149',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '90',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '29',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '113',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '289',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '115',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '298',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '237',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '162',
        },
        {
          yes: 1,
          no: 3,
          abstination: 0,
          total: 4,
          constituency: '188',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '98',
        },
        {
          yes: 1,
          no: 2,
          abstination: 0,
          total: 3,
          constituency: '145',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '130',
        },
        {
          yes: 2,
          no: 3,
          abstination: 0,
          total: 5,
          constituency: '242',
        },
        {
          yes: 1,
          no: 9,
          abstination: 0,
          total: 10,
          constituency: '15',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '144',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '253',
        },
        {
          yes: 2,
          no: 6,
          abstination: 0,
          total: 8,
          constituency: '85',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '295',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '294',
        },
        {
          yes: 1,
          no: 3,
          abstination: 0,
          total: 4,
          constituency: '7',
        },
        {
          yes: 0,
          no: 12,
          abstination: 0,
          total: 12,
          constituency: '58',
        },
        {
          yes: 0,
          no: 11,
          abstination: 0,
          total: 11,
          constituency: '268',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '57',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '269',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '293',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '50',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '95',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '195',
        },
        {
          yes: 1,
          no: 1,
          abstination: 0,
          total: 2,
          constituency: '52',
        },
        {
          yes: 1,
          no: 1,
          abstination: 0,
          total: 2,
          constituency: '275',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '185',
        },
        {
          yes: 0,
          no: 0,
          abstination: 1,
          total: 1,
          constituency: '284',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '48',
        },
        {
          yes: 0,
          no: 10,
          abstination: 2,
          total: 12,
          constituency: '281',
        },
        {
          yes: 0,
          no: 12,
          abstination: 0,
          total: 12,
          constituency: '193',
        },
        {
          yes: 2,
          no: 10,
          abstination: 0,
          total: 12,
          constituency: '80',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '241',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '274',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '78',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '106',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '266',
        },
        {
          yes: 2,
          no: 11,
          abstination: 0,
          total: 13,
          constituency: '218',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '73',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '125',
        },
        {
          yes: 1,
          no: 14,
          abstination: 0,
          total: 15,
          constituency: '214',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '171',
        },
        {
          yes: 0,
          no: 1,
          abstination: 1,
          total: 2,
          constituency: '119',
        },
        {
          yes: 5,
          no: 5,
          abstination: 0,
          total: 10,
          constituency: '191',
        },
        {
          yes: 0,
          no: 8,
          abstination: 1,
          total: 9,
          constituency: '263',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '207',
        },
        {
          yes: 0,
          no: 9,
          abstination: 1,
          total: 10,
          constituency: '222',
        },
        {
          yes: 2,
          no: 13,
          abstination: 0,
          total: 15,
          constituency: '54',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '240',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '64',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '132',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '20',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '178',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '233',
        },
        {
          yes: 0,
          no: 4,
          abstination: 1,
          total: 5,
          constituency: '189',
        },
        {
          yes: 1,
          no: 12,
          abstination: 0,
          total: 13,
          constituency: '265',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '77',
        },
        {
          yes: 0,
          no: 5,
          abstination: 1,
          total: 6,
          constituency: '97',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '49',
        },
        {
          yes: 0,
          no: 9,
          abstination: 1,
          total: 10,
          constituency: '152',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '74',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '244',
        },
        {
          yes: 0,
          no: 5,
          abstination: 1,
          total: 6,
          constituency: '110',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '19',
        },
        {
          yes: 0,
          no: 22,
          abstination: 0,
          total: 22,
          constituency: '159',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '236',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '169',
        },
        {
          yes: 0,
          no: 0,
          abstination: 1,
          total: 1,
          constituency: '151',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '267',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '30',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '82',
        },
        {
          yes: 0,
          no: 13,
          abstination: 0,
          total: 13,
          constituency: '261',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '3',
        },
        {
          yes: 1,
          no: 5,
          abstination: 0,
          total: 6,
          constituency: '262',
        },
        {
          yes: 1,
          no: 4,
          abstination: 2,
          total: 7,
          constituency: '40',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '285',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '288',
        },
        {
          yes: 3,
          no: 5,
          abstination: 0,
          total: 8,
          constituency: '87',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '32',
        },
        {
          yes: 1,
          no: 1,
          abstination: 0,
          total: 2,
          constituency: '202',
        },
        {
          yes: 2,
          no: 7,
          abstination: 1,
          total: 10,
          constituency: '18',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '249',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '167',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '100',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '282',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '128',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '292',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '212',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '256',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '1',
        },
        {
          yes: 1,
          no: 4,
          abstination: 0,
          total: 5,
          constituency: '134',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '103',
        },
        {
          yes: 1,
          no: 1,
          abstination: 1,
          total: 3,
          constituency: '137',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '190',
        },
        {
          yes: 0,
          no: 7,
          abstination: 0,
          total: 7,
          constituency: '9',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '140',
        },
        {
          yes: 1,
          no: 5,
          abstination: 1,
          total: 7,
          constituency: '245',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '102',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '6',
        },
        {
          yes: 1,
          no: 6,
          abstination: 0,
          total: 7,
          constituency: '161',
        },
        {
          yes: 2,
          no: 10,
          abstination: 0,
          total: 12,
          constituency: '260',
        },
        {
          yes: 3,
          no: 13,
          abstination: 0,
          total: 16,
          constituency: '107',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '213',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '231',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '5',
        },
        {
          yes: 1,
          no: 7,
          abstination: 0,
          total: 8,
          constituency: '183',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '133',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '165',
        },
        {
          yes: 0,
          no: 10,
          abstination: 0,
          total: 10,
          constituency: '104',
        },
        {
          yes: 0,
          no: 1,
          abstination: 0,
          total: 1,
          constituency: '141',
        },
        {
          yes: 1,
          no: 13,
          abstination: 0,
          total: 14,
          constituency: '205',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '120',
        },
        {
          yes: 1,
          no: 2,
          abstination: 0,
          total: 3,
          constituency: '34',
        },
        {
          yes: 0,
          no: 2,
          abstination: 0,
          total: 2,
          constituency: '146',
        },
        {
          yes: 0,
          no: 3,
          abstination: 0,
          total: 3,
          constituency: '286',
        },
        {
          yes: 0,
          no: 8,
          abstination: 0,
          total: 8,
          constituency: '136',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '108',
        },
        {
          yes: 2,
          no: 6,
          abstination: 0,
          total: 8,
          constituency: '182',
        },
        {
          yes: 0,
          no: 8,
          abstination: 1,
          total: 9,
          constituency: '247',
        },
        {
          yes: 1,
          no: 3,
          abstination: 0,
          total: 4,
          constituency: '248',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '56',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '197',
        },
        {
          yes: 1,
          no: 8,
          abstination: 0,
          total: 9,
          constituency: '138',
        },
        {
          yes: 0,
          no: 9,
          abstination: 0,
          total: 9,
          constituency: '60',
        },
        {
          yes: 0,
          no: 6,
          abstination: 0,
          total: 6,
          constituency: '123',
        },
        {
          yes: 0,
          no: 5,
          abstination: 0,
          total: 5,
          constituency: '131',
        },
        {
          yes: 0,
          no: 4,
          abstination: 0,
          total: 4,
          constituency: '238',
        },
      ],
    },
  },
};
